# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
 name: 'azureagent'


stages:
- stage: SonarQubeAnalysis
  displayName: SonarQube Analysis
  jobs:
  - job: SonarQubeAnalysisJob
    steps:
    - task: SonarQubePrepare@7
      inputs:
        SonarQube: 'sonarqube-connection'
        scannerMode: 'cli'
        cliScannerVersion: '1'
        configMode: 'manual'
        cliProjectKey: 'flask-app'
        cliProjectName: 'flask-app'
        cliSources: '.'

    - script:  |
        pip install -r requirements.txt
      displayName: 'Install Python Requirements'

    - task: SonarQubeAnalyze@7 
    
    - task: SonarQubePublish@7
      inputs:
        pollingTimeoutSec: '300'


- stage: Build
  dependsOn: SonarQubeAnalysis
  condition: succeeded()
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)


- stage: Push
  dependsOn: Build
  condition: succeeded()
  displayName: Push image
  jobs:
  - job: Push
    displayName: Push
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'vmprojectacr'
        command: 'push'