# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'vmproject'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)


- stage: Push
  displayName: Push image
  jobs:
  - job: Push
    displayName: Push
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'vmprojectacr'
        command: 'push'