# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
 name: 'azureagent'


stages:
- stage: SonarqubeSetup
  displayName: SonarqubeSetup
  jobs:
  - job: SonarqubeSetup
    displayName: SonarqubeSetup
    steps:
    - task: SonarQubePrepare@7
      inputs:
        SonarQube: 'sonarqube-connection'
        scannerMode: 'cli'
        configMode: 'manual'
        cliProjectKey: 'my-flask-app'
        cliProjectName: 'my-flask-app'
        cliSources: '.'


- stage: SonarqubeRunCodeAnalysis
  dependsOn: SonarqubeSetup
  condition: succeeded()
  displayName: SonarqubeRunCodeAnalysis
  jobs:
  - job: SonarqubeRunCodeAnalysis
    displayName: SonarqubeRunCodeAnalysis
    steps:
    - task: SonarQubeAnalyze@7
      inputs:
        jdkversion: 'JAVA_HOME'


- stage: Build
  dependsOn: SonarqubeRunCodeAnalysis
  condition: succeeded()
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)


- stage: Push
  dependsOn: Build
  condition: succeeded()
  displayName: Push image
  jobs:
  - job: Push
    displayName: Push
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'vmprojectacr'
        command: 'push'